# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='a1',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a10',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a2',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a3',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a4',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a5',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a6',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a7',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a8',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='a9',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='q1',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q10',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q2',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q3',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q4',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q5',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q6',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q7',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q8',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='q9',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=3),
        ),
    ]
