# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180612_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='a10',
            new_name='a0',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='q10',
            new_name='q0',
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
