# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180612_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('score', models.IntegerField(max_length=2)),
                ('data', models.ForeignKey(on_delete='id', to='quiz.Data', to_field='models.CASCADE')),
            ],
        ),
    ]
