# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(max_length=2),
        ),
    ]
